name: lh-to-coq 
# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
ghc-options:
    -fhide-source-paths
    -freverse-errors

executable:
  main: Main.hs
  source-dirs: app
  dependencies: lh-to-coq

dependencies:
  - liquid-base
  - liquidhaskell
  - containers
  - liquid-fixpoint
  - mtl
  - ghc

library:
  source-dirs: src
  exposed-modules: LHToCoq
