# Taken from https://github.com/erikmd/docker-coq-github-action-demo
name: Test Coq Files

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - '**'

jobs:
  testfiles:
    runs-on: ubuntu-latest  # container actions require GNU/Linux
    strategy:
      matrix:
        coq_version:
          - '8.16'
          - dev
        ocaml_version: ['default']
      fail-fast: false  # don't stop jobs if one fails
    steps:
      - uses: actions/checkout@v3
      - uses: coq-community/docker-coq-action@v1 
        with:
          opam_file: 'lh-to-coq.opam'
          coq_version: ${{ matrix.coq_version }}
          ocaml_version: ${{ matrix.ocaml_version }}

